language: node_js
node_js:
  - '4.2'
before_install:
    - cd front-end
install:
    - npm install
    - npm run build-dev &
    # - gulp --cordova "prepare"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
    - cd ../back-end
    - npm install
    - npm run start-dev &
    - sleep 5
    - npm test
    - cd ../front-end
    - npm test
